meta_learner: supervised
meta_model: seq
learner_model: bert
learner_params:
  num_outputs:
    ner: 19
  embed_dim: 768
  dropout_ratio: 0.1
  fine_tune_layers: 10
  adapter_mode: False
vectors: bert
meta_lr: 0.00001
batch_size: 32
eval_batch_size: 64
num_meta_epochs: 5
early_stopping: 2
device: cuda:0
