meta_learner: maml
fomaml: False
proto_maml: True
meta_model: seq
learner_model: bert
learner_params:
  hidden_size: 192
  num_outputs:
    ner: var
  embed_dim: 768
  dropout_ratio: 0
  fine_tune_layers: 1
vectors: bert
output_lr: 0.001
learner_lr: 0.001
meta_lr: 0.0001
meta_batch_size: 4
num_shots:
  ner: 5
num_updates: 1
num_test_samples:
  ner: 5
num_train_episodes:
  ner: 50
num_val_episodes:
  ner: 10
num_test_episodes:
  ner: 10
num_meta_epochs: 20
early_stopping: 2
device: cuda:0
