meta_learner: maml
fomaml: True
proto_maml: False
meta_model: seq
learner_model: bert
learner_params:
  hidden_size: 192
  num_outputs:
    ner: var
  embed_dim: 768
  dropout_ratio: 0
vectors: bert
output_lr: 0.1
learner_lr: 0.001
meta_lr: 0.00005
meta_batch_size: 4
num_shots:
  ner: 5
num_updates: 7
num_test_samples:
  ner: 5
num_train_episodes:
  ner: 50
num_val_episodes:
  ner: 10
num_test_episodes:
  ner: 10
num_meta_epochs: 100
early_stopping: 2
device: cuda:0,1